# Generated by Django 5.0.4 on 2024-04-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('ingredients', models.TextField(default=' ')),
                ('directions', models.TextField(default=' ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/')),
                ('added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
